### ISSUE TITLE
UI Adjustments

### ISSUE THREAD

**Issue by sarahsga** [hadiakhan785/weather-app-2#2]
Nice work on the app UI overall. Just needs a few tiny adjustments:

### 1. Background Color
The Yellow in the background is too bright, probably not a good color for the background. I would suggest you look up some weather apps in Google Images and use a color from there. Or, choose a muted color from [Flat Colors Palette](https://flatuicolors.com/)  or [Material Colors Palette](https://material.io/guidelines/style/color.html#color-color-palette). The best option is to take inspiration from somewhere on the internet

### 2. give the `Cities Weather` heading a top margin

![screencapture-hadiakhan785-github-io-weather-app-2-2018-08-27-19_06_03](https://user-images.githubusercontent.com/10798986/44664314-4f44ec00-aa2c-11e8-8f1d-5c8a3f810e30.png)

### 3. Styling of weather info
The weather info in the image below can be styled better. Maybe take inspration from another Weather App for this info, as you [PNG reference](https://drive.google.com/file/d/12mPM8LQMT5fqoY6UCJBwia1CkQ7QHxr8/view) does not show this information

![screen shot 2018-08-27 at 19 07 06](https://user-images.githubusercontent.com/10798986/44664410-9b902c00-aa2c-11e8-8be6-4eda8ce255fc.png)

**Comment by hadiakhan785** [comment]
done
